// bus_weak_cells.v - test-only "weak / discharge-only" inverting tristate for
// the precharged inverse-hold buses of the PPU testbench (issue #390).
//
// Used by ppu2_weakbus.v (generated by gen_weakbus.py) for the six oa-chain
// nodes (w497/w146/w500/w554/w641/w49). Real behaviour of such nodes:
// precharged HIGH, each mux group can only discharge them (pull low) while
// enabled; a group writing a logic 1 simply does not discharge. Statically
// modelling every group as a strong inverting tristate (dmg_notif0: x = ~a)
// makes overlapping enables drive the same node to opposite rails
// (contention x) and leaves the node floating (x through the oa NOT gates)
// when no group is enabled.
//
// dmg_notif0_od is the open-drain form: strong 0 while enabled AND a==1,
// hi-Z otherwise; the node is held at its precharge level 1 by pullup()
// keepers inserted by gen_weakbus.py. Polarity is unchanged for a single
// driver: a==0 -> hi-Z -> keeper 1 (= ~a), a==1 -> 0 (= ~a). Unknown data
// (a = x) is treated as "no discharge".
//
// This is a BUS MODELLING choice for the simulator only - it is NOT a
// change to HDL/soc/ppu2.v (see Readme.md "Bus modelling").

module dmg_notif0_od ( n_ena, a, x);

	input wire n_ena;
	input wire a;
	output wire x;

	assign x = (n_ena === 1'b0 && a === 1'b1) ? 1'b0 : 1'bz;

endmodule
