del alu_trees.v

echo // Automagically generated by MakeNandTree py >> alu_trees.v
echo. >> alu_trees.v

py -3 MakeNandTree.py --tree {alu0}{w24,nIR3,nIR4,nIR5}{w10,IR5}{w10,IR4}{w10,IR3} --output_name "a[0]" >> alu_trees.v
py -3 MakeNandTree.py --tree {alu0}{w24,nIR3,nIR4,nIR5}{w10,IR5}{w10,IR4}{w10,IR3} --output_name "a[1]" >> alu_trees.v
py -3 MakeNandTree.py --tree {alu0}{w24,nIR3,nIR4,nIR5}{w10,IR5}{w10,IR4}{w10,IR3} --output_name "a[2]" >> alu_trees.v
